@host = https://localhost:7036

POST {{host}}/authentication/register
Content-Type: application/json

{
   "firstName" : "Shakil",
   "lastName" : "Victor",
   "email" : "shakilvictor9102@gmail.com",
   "password" : "Shakil321!"
}
